In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("sleep_disorder_dataset.csv")

In [3]:
df

,Patient_ID,Age,Gender,Sleep_Disorder_Type,AHI_Score,SaO2_Level,OCR_Extracted_Text,Diagnosis_Confirmed
0,P0001,54,Female,Restless Leg Syndrome,44.11,77.59,Patient P0001 diagnosed with Restless Leg Synd...,1
1,P0002,17,Female,Restless Leg Syndrome,33.55,76.22,Patient P0002 diagnosed with Restless Leg Synd...,1
2,P0003,74,Male,Insomnia,12.91,89.53,Patient P0003 diagnosed with Insomnia.,1
3,P0004,63,Male,Restless Leg Syndrome,33.73,85.65,Patient P0004 diagnosed with Restless Leg Synd...,1
4,P0005,23,Female,Insomnia,14.84,88.70,Patient P0005 diagnosed with Insomnia.,1
...,...,...,...,...,...,...,...,...
995,P0996,23,Female,Insomnia,41.57,83.14,Patient P0996 diagnosed with Insomnia.,1
996,P0997,49,Female,No Disorder,42.12,84.85,Patient P0997 diagnosed with No Disorder.,1
997,P0998,75,Male,Obstructive Sleep Apnea,18.66,90.08,Patient P0998 diagnosed with Obstructive Sleep...,1
998,P0999,55,Female,Insomnia,31.60,95.04,Patient P0999 diagnosed with Insomnia.,1


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Patient_ID           1000 non-null   object 
 1   Age                  1000 non-null   int64  
 2   Gender               1000 non-null   object 
 3   Sleep_Disorder_Type  1000 non-null   object 
 4   AHI_Score            1000 non-null   float64
 5   SaO2_Level           1000 non-null   float64
 6   OCR_Extracted_Text   1000 non-null   object 
 7   Diagnosis_Confirmed  1000 non-null   int64  
dtypes: float64(2), int64(2), object(4)
memory usage: 62.6+ KB


In [5]:
df.head()

,Patient_ID,Age,Gender,Sleep_Disorder_Type,AHI_Score,SaO2_Level,OCR_Extracted_Text,Diagnosis_Confirmed
0,P0001,54,Female,Restless Leg Syndrome,44.11,77.59,Patient P0001 diagnosed with Restless Leg Synd...,1
1,P0002,17,Female,Restless Leg Syndrome,33.55,76.22,Patient P0002 diagnosed with Restless Leg Synd...,1
2,P0003,74,Male,Insomnia,12.91,89.53,Patient P0003 diagnosed with Insomnia.,1
3,P0004,63,Male,Restless Leg Syndrome,33.73,85.65,Patient P0004 diagnosed with Restless Leg Synd...,1
4,P0005,23,Female,Insomnia,14.84,88.70,Patient P0005 diagnosed with Insomnia.,1


In [6]:
df.tail()

,Patient_ID,Age,Gender,Sleep_Disorder_Type,AHI_Score,SaO2_Level,OCR_Extracted_Text,Diagnosis_Confirmed
995,P0996,23,Female,Insomnia,41.57,83.14,Patient P0996 diagnosed with Insomnia.,1
996,P0997,49,Female,No Disorder,42.12,84.85,Patient P0997 diagnosed with No Disorder.,1
997,P0998,75,Male,Obstructive Sleep Apnea,18.66,90.08,Patient P0998 diagnosed with Obstructive Sleep...,1
998,P0999,55,Female,Insomnia,31.60,95.04,Patient P0999 diagnosed with Insomnia.,1
999,P1000,11,Female,Restless Leg Syndrome,4.77,86.74,Patient P1000 diagnosed with Restless Leg Synd...,1


In [7]:
df.describe()

,Age,AHI_Score,SaO2_Level,Diagnosis_Confirmed
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,40.490000,25.715150,87.482860,0.884000
std,22.659642,14.324888,7.179349,0.320385
min,3.000000,0.020000,75.000000,0.000000
25%,21.000000,13.450000,81.335000,1.000000
50%,40.000000,26.395000,87.610000,1.000000
75%,60.000000,38.105000,93.790000,1.000000
max,80.000000,49.990000,99.940000,1.000000


In [8]:
df.ndim

2

In [9]:
df.dtypes

Patient_ID              object
Age                      int64
Gender                  object
Sleep_Disorder_Type     object
AHI_Score              float64
SaO2_Level             float64
OCR_Extracted_Text      object
Diagnosis_Confirmed      int64
dtype: object

In [10]:
df.shape

(1000, 8)

In [11]:
df.isnull().sum()

Patient_ID             0
Age                    0
Gender                 0
Sleep_Disorder_Type    0
AHI_Score              0
SaO2_Level             0
OCR_Extracted_Text     0
Diagnosis_Confirmed    0
dtype: int64

In [12]:
df.notnull().sum()

Patient_ID             1000
Age                    1000
Gender                 1000
Sleep_Disorder_Type    1000
AHI_Score              1000
SaO2_Level             1000
OCR_Extracted_Text     1000
Diagnosis_Confirmed    1000
dtype: int64

In [13]:
df = df.drop(["Patient_ID", "OCR_Extracted_Text"], axis=1)

In [14]:
df

,Age,Gender,Sleep_Disorder_Type,AHI_Score,SaO2_Level,Diagnosis_Confirmed
0,54,Female,Restless Leg Syndrome,44.11,77.59,1
1,17,Female,Restless Leg Syndrome,33.55,76.22,1
2,74,Male,Insomnia,12.91,89.53,1
3,63,Male,Restless Leg Syndrome,33.73,85.65,1
4,23,Female,Insomnia,14.84,88.70,1
...,...,...,...,...,...,...
995,23,Female,Insomnia,41.57,83.14,1
996,49,Female,No Disorder,42.12,84.85,1
997,75,Male,Obstructive Sleep Apnea,18.66,90.08,1
998,55,Female,Insomnia,31.60,95.04,1


In [15]:
import sklearn as sk
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,classification_report

In [16]:
le = LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])
df["Sleep_Disorder_Type"]=le.fit_transform(df["Sleep_Disorder_Type"])

In [17]:
df

,Age,Gender,Sleep_Disorder_Type,AHI_Score,SaO2_Level,Diagnosis_Confirmed
0,54,0,4,44.11,77.59,1
1,17,0,4,33.55,76.22,1
2,74,1,0,12.91,89.53,1
3,63,1,4,33.73,85.65,1
4,23,0,0,14.84,88.70,1
...,...,...,...,...,...,...
995,23,0,0,41.57,83.14,1
996,49,0,2,42.12,84.85,1
997,75,1,3,18.66,90.08,1
998,55,0,0,31.60,95.04,1


In [18]:
x=df.drop(columns="Diagnosis_Confirmed")

In [19]:
y=df["Diagnosis_Confirmed"]

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,random_state=50)

In [21]:
scaler=StandardScaler()
x_train_scale=scaler.fit_transform(x_train)
x_test_scale=scaler.transform(x_test)

### Logistic Regression

In [22]:
model=LogisticRegression()

In [23]:
model.fit(x_train_scale,y_train)

LogisticRegression()

In [24]:
y_pred = model.predict(x_test_scale)

In [25]:
acc=accuracy_score(y_test,y_pred)

In [26]:
acc

0.965

In [27]:
cm=confusion_matrix(y_test,y_pred)

In [28]:
cm

array([[ 13,   5],
       [  2, 180]])

In [29]:
precision=precision_score(y_test,y_pred)

In [30]:
precision

np.float64(0.972972972972973)

In [31]:
recall=recall_score(y_test,y_pred)

In [32]:
recall

np.float64(0.989010989010989)

In [33]:
f1=f1_score(y_test,y_pred)

In [34]:
f1

np.float64(0.9809264305177112)

In [35]:
report=classification_report(y_test,y_pred)

In [36]:
print(report)

              precision    recall  f1-score   support

           0       0.87      0.72      0.79        18
           1       0.97      0.99      0.98       182

    accuracy                           0.96       200
   macro avg       0.92      0.86      0.88       200
weighted avg       0.96      0.96      0.96       200



### RandomForestClassifier

In [37]:
rf=RandomForestClassifier(n_estimators=100)

In [38]:
rf.fit(x_train_scale,y_train)

RandomForestClassifier()

In [39]:
y_pred_rf=rf.predict(x_test_scale)

In [40]:
acc_rf=accuracy_score(y_test,y_pred_rf)

In [41]:
acc_rf

1.0

In [42]:
cm_rf=confusion_matrix(y_test,y_pred_rf)

In [43]:
cm_rf

array([[ 18,   0],
       [  0, 182]])

In [44]:
precision_rf=precision_score(y_test,y_pred_rf)

In [45]:
precision_rf

np.float64(1.0)

In [46]:
recall_rf=recall_score(y_test,y_pred_rf)

In [47]:
recall_rf

np.float64(1.0)

In [48]:
f1_rf=f1_score(y_test,y_pred_rf)

In [49]:
f1_rf

np.float64(1.0)

In [50]:
report_rf=classification_report(y_test,y_pred_rf)

In [51]:
print(report_rf)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00       182

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



### Support Vector Machine

In [52]:
clf = SVC(kernel='linear') 

In [53]:
clf.fit(x_train_scale, y_train)

SVC(kernel='linear')

In [54]:
y_pred_clf = clf.predict(x_test_scale)

In [55]:
acc_clf=accuracy_score(y_test,y_pred_clf)

In [56]:
acc_clf

0.97

In [57]:
cm_clf=confusion_matrix(y_test,y_pred_clf)

In [58]:
cm_clf

array([[ 14,   4],
       [  2, 180]])

In [59]:
precision_clf=precision_score(y_test,y_pred_clf)

In [60]:
precision_clf

np.float64(0.9782608695652174)

In [61]:
recall_rf=recall_score(y_test,y_pred_rf)

In [62]:
recall_rf

np.float64(1.0)

In [63]:
f1_rf=f1_score(y_test,y_pred_rf)

In [64]:
f1_rf

np.float64(1.0)

In [65]:
report_rf=classification_report(y_test,y_pred_rf)

In [66]:
print(report_rf)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00       182

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

